const ENTITY_CONFIG = {
  products: { sheet: 'Products', id: 'SKU' }, orders: { sheet: 'Orders', id: '주문ID' }, suppliers: { sheet: 'Suppliers', id: '공급처ID' },
};
function entity_(payload) { const key = String(payload && payload.entity || '').toLowerCase(); if (!ENTITY_CONFIG[key]) throw new Error('unsupported_entity'); return { key, ...ENTITY_CONFIG[key] }; }
function table_(name) { const sheet = book_().getSheetByName(name); if (!sheet) throw new Error('sheet_not_found'); const headers = sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0].map(String); return { sheet, headers }; }
function findRow_(table, idHeader, id) { const index = table.headers.indexOf(idHeader); if (index < 0 || table.sheet.getLastRow() < 2) return -1; const values = table.sheet.getRange(2,index+1,table.sheet.getLastRow()-1,1).getDisplayValues(); const found = values.findIndex(row => String(row[0]).trim() === id); return found < 0 ? -1 : found + 2; }
function listRecords_(payload) { const meta=entity_(payload), table=table_(meta.sheet); if(table.sheet.getLastRow()<2)return{ok:true,records:[]}; const rows=table.sheet.getRange(2,1,table.sheet.getLastRow()-1,table.headers.length).getDisplayValues(); const deleted=table.headers.indexOf('삭제여부'), idIndex=table.headers.indexOf(meta.id); const records=rows.filter(row=>String(row[idIndex]||'').trim() && (deleted<0 || String(row[deleted]).toUpperCase()!=='Y')).map(row=>Object.fromEntries(table.headers.map((header,i)=>[header,row[i]]))); return{ok:true,entity:meta.key,records}; }
function createRecord_(payload) { const meta=entity_(payload),table=table_(meta.sheet),record=payload.record||{},id=String(record[meta.id]||'').trim(); if(!id)throw new Error('missing_id'); if(findRow_(table,meta.id,id)>0)throw new Error('duplicate_id'); table.sheet.appendRow(table.headers.map(header=>header==='삭제여부'?'N':header==='생성일'?new Date():header==='수정자'?'KORUAL Platform':record[header]??'')); audit_('CREATE',meta.sheet,id,record); return{ok:true,id}; }
function updateRecord_(payload) { const meta=entity_(payload),table=table_(meta.sheet),record=payload.record||{},id=String(payload.id||record[meta.id]||''),row=findRow_(table,meta.id,id); if(row<2)throw new Error('record_not_found'); const current=table.sheet.getRange(row,1,1,table.headers.length).getValues()[0]; const next=table.headers.map((header,i)=>header===meta.id?current[i]:header==='수정일'?new Date():header==='수정자'?'KORUAL Platform':Object.prototype.hasOwnProperty.call(record,header)?record[header]:current[i]); table.sheet.getRange(row,1,1,next.length).setValues([next]); audit_('UPDATE',meta.sheet,id,record); return{ok:true,id}; }
function deleteRecord_(payload) { const meta=entity_(payload),table=table_(meta.sheet),id=String(payload.id||''),row=findRow_(table,meta.id,id),index=table.headers.indexOf('삭제여부'); if(row<2)throw new Error('record_not_found'); if(index<0)throw new Error('delete_column_missing'); table.sheet.getRange(row,index+1).setValue('Y'); audit_('DELETE',meta.sheet,id,{softDelete:true}); return{ok:true,id,deleted:true}; }
function audit_(action,sheet,id,detail) { const log=book_().getSheetByName('Audit_Log'); if(log)log.appendRow([Utilities.getUuid(),new Date(),action,sheet,id,JSON.stringify(detail||{}),'KORUAL Platform']); }
