import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Package,ShoppingBag,FolderTree,PanelsTopLeft,Users,Plug,Zap,BarChart3,Settings,Search,Plus,Pencil,Trash2,X,Check,AlertTriangle,Download,Menu,Cloud,LogIn,LogOut,Bell,HelpCircle,ChevronRight}from'lucide-react';
import'./styles.css';
import{supabase}from'./supabase';
import{fromCloud,getCloudResource,toCloud}from'./data/database';

const seed={
 products:[
  {id:1,name:'KORUAL 시그니처 호텔 타월',sku:'KRU-000124',category:'타월',price:42000,stock:128,status:'판매 중'},
  {id:2,name:'크림 엠보 페이스 타월 세트',sku:'KRU-000123',category:'타월',price:35000,stock:84,status:'판매 중'},
  {id:3,name:'호텔 홈스파 트래블 키트',sku:'KRU-000122',category:'홈스파',price:49000,stock:16,status:'재고 부족'},
  {id:4,name:'KORUAL 골드 디퓨저 200ml',sku:'KRU-000121',category:'향기',price:38000,stock:0,status:'품절'},
 ],
 orders:[{id:10031,name:'김민준',sku:'KRU-000124',category:'결제완료',price:84000,stock:2,status:'배송 준비'},{id:10030,name:'박서연',sku:'KRU-000123',category:'배송',price:35000,stock:1,status:'배송 중'}],
 categories:[{id:1,name:'타월',sku:'TOWEL',category:'Brand',price:2,stock:2,status:'사용'},{id:2,name:'홈스파',sku:'SPA',category:'Brand',price:1,stock:1,status:'사용'}],
 content:[{id:1,name:'첫 구매 3,000원 할인',sku:'BNR-001',category:'메인 배너',price:0,stock:1,status:'게시 중'},{id:2,name:'호텔의 휴식을 집으로',sku:'STORY-01',category:'브랜드 스토리',price:0,stock:1,status:'초안'}],
 customers:[{id:1,name:'김서연',sku:'korual@naver.com',category:'VIP',price:119000,stock:3,status:'활성'},{id:2,name:'이민준',sku:'010-****-1247',category:'일반',price:84000,stock:1,status:'활성'}],
 integrations:[{id:1,name:'Supabase',sku:'데이터·인증',category:'클라우드',price:0,stock:4,status:'정상'},{id:2,name:'Cafe24',sku:'OAuth 대기',category:'쇼핑몰',price:0,stock:2,status:'설정 필요'},{id:3,name:'GitHub',sku:'PR #5',category:'소스',price:0,stock:1,status:'연결됨'},{id:4,name:'Vercel',sku:'Production',category:'배포',price:0,stock:1,status:'연결됨'}],
 automation:[{id:1,name:'저재고 경보',sku:'AUTO-STOCK',category:'재고',price:10,stock:1,status:'실행 중'},{id:2,name:'입금대기 알림',sku:'AUTO-BANK',category:'주문',price:30,stock:1,status:'실행 중'},{id:3,name:'배송지연 카카오 알림톡',sku:'AUTO-KAKAO-DELAY',category:'배송',price:60,stock:1,status:'웹훅 설정 필요'},{id:4,name:'SEO 기회 수집',sku:'AUTO-SEO',category:'트래픽',price:1440,stock:1,status:'준비'}],
 analytics:[{id:1,name:'상품 조회',sku:'product_view',category:'퍼널',price:1240,stock:18,status:'상승'},{id:2,name:'장바구니',sku:'add_to_cart',category:'퍼널',price:186,stock:9,status:'관찰'},{id:3,name:'계좌이체 주문',sku:'bank_order',category:'전환',price:21,stock:4,status:'핵심'}],
 settings:[{id:1,name:'관리자 이메일',sku:'korual@naver.com',category:'보안',price:0,stock:1,status:'보호됨'},{id:2,name:'계좌이체 우선',sku:'PAY-BANK',category:'결제',price:0,stock:1,status:'사용'},{id:3,name:'데이터 백업',sku:'BACKUP-DAILY',category:'시스템',price:1,stock:1,status:'매일'}]
};
const sections={dashboard:['대시보드','스토어 운영 현황을 한눈에 확인하세요.'],products:['상품 관리','상품을 등록, 수정, 삭제하고 판매 상태를 관리하세요.'],orders:['주문 관리','계좌이체 입금과 배송 진행 상황을 관리하세요.'],categories:['카테고리','판매 구조와 진열 순서를 관리하세요.'],content:['콘텐츠','배너와 브랜드 콘텐츠를 관리하세요.'],customers:['고객 관리','구매 이력과 고객 등급을 관리하세요.'],integrations:['연동 관리','클라우드와 외부 서비스 연결 상태를 관리하세요.'],automation:['자동화','반복 업무와 알림 규칙을 관리하세요.'],analytics:['통계','유입부터 구매까지 전환 흐름을 분석하세요.'],settings:['시스템 설정','권한, 결제, 백업 정책을 관리하세요.']};
const nav=[['dashboard','대시보드',LayoutDashboard],['products','상품 관리',Package],['orders','주문 관리',ShoppingBag],['categories','카테고리',FolderTree],['content','콘텐츠',PanelsTopLeft],['customers','고객 관리',Users],['integrations','연동 관리',Plug],['automation','자동화',Zap],['analytics','통계',BarChart3],['settings','시스템 설정',Settings]];
const mobileNav=nav.filter(([id])=>['dashboard','products','orders','automation'].includes(id));
const groupBefore={dashboard:'운영 개요',products:'스토어 운영',customers:'고객·성장',integrations:'시스템'};
const pageUi={
 products:{columns:['상품','SKU','카테고리','판매가','재고','판매 상태'],stats:['전체 상품','판매 가능','총 재고','판매가 합계'],fields:['상품명','SKU','카테고리','판매 상태','판매가','재고'],add:'상품 등록',money:true},
 orders:{columns:['고객','주문번호','결제 구분','주문금액','수량','처리 상태'],stats:['전체 주문','처리 중','주문 수량','주문금액 합계'],fields:['고객명','주문번호','결제 구분','처리 상태','주문금액','수량'],add:'주문 등록',money:true},
 categories:{columns:['카테고리','코드','상위 분류','진열 순서','하위 수','사용 상태'],stats:['전체 분류','사용 중','하위 분류','진열 순서 합계'],fields:['카테고리명','코드','상위 분류','사용 상태','진열 순서','하위 수'],add:'카테고리 추가'},
 content:{columns:['콘텐츠','코드','유형','우선순위','노출 수','게시 상태'],stats:['전체 콘텐츠','게시 가능','노출 설정','우선순위 합계'],fields:['콘텐츠명','코드','콘텐츠 유형','게시 상태','우선순위','노출 수'],add:'콘텐츠 추가'},
 customers:{columns:['고객','연락처','등급','누적 구매액','주문 횟수','고객 상태'],stats:['전체 고객','활성 고객','총 주문 횟수','누적 구매액'],fields:['고객명','연락처','고객 등급','고객 상태','누적 구매액','주문 횟수'],add:'고객 추가',money:true},
 integrations:{columns:['서비스','연결 정보','구분','비용','기능 수','연결 상태'],stats:['전체 연동','정상 연결','연결 기능','월 비용'],fields:['서비스명','연결 정보','서비스 구분','연결 상태','월 비용','기능 수'],add:'연동 추가',money:true},
 automation:{columns:['자동화','규칙 코드','업무 영역','실행 주기(분)','활성 규칙','실행 상태'],stats:['전체 규칙','실행 가능','활성 규칙','주기 합계(분)'],fields:['자동화명','규칙 코드','업무 영역','실행 상태','실행 주기(분)','활성 규칙'],add:'규칙 추가'},
 analytics:{columns:['이벤트','이벤트 코드','퍼널 단계','발생 수','전환 지표','추세'],stats:['측정 이벤트','상승 지표','전환 지표','총 발생 수'],fields:['이벤트명','이벤트 코드','퍼널 단계','추세','발생 수','전환 지표'],add:'지표 추가'},
 settings:{columns:['설정','설정값','영역','주기','적용 수','상태'],stats:['전체 설정','안전 설정','적용 수','주기 합계'],fields:['설정명','설정값','설정 영역','상태','주기','적용 수'],add:'설정 추가'}
};
const blank={name:'',sku:'',category:'타월',price:0,stock:0,status:'판매 중'};

function App(){
 const[data,setData]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('korual-admin'));return saved?{...seed,...saved}:seed}catch{return seed}});
 const[page,setPage]=useState('dashboard'),[query,setQuery]=useState(''),[status,setStatus]=useState('전체'),[editor,setEditor]=useState(null),[remove,setRemove]=useState(null),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false);
 const[session,setSession]=useState(null),[authOpen,setAuthOpen]=useState(false),[email,setEmail]=useState(''),[syncing,setSyncing]=useState(false);
 useEffect(()=>localStorage.setItem('korual-admin',JSON.stringify(data)),[data]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{const onKey=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.global input')?.focus()}if(e.key==='Escape'){setEditor(null);setRemove(null);setAuthOpen(false);setMobile(false)}};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data:{session}})=>setSession(session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setSession(session));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{const resource=getCloudResource(page);if(!session||!resource)return;let live=true;setSyncing(true);supabase.from(resource.table).select('*').order(resource.orderBy,{ascending:false}).then(({data:items,error})=>{if(!live)return;if(error)setToast('클라우드 권한 확인이 필요합니다.');else setData(d=>({...d,[page]:items.map(fromCloud[page])}));setSyncing(false)});return()=>{live=false}},[session,page]);
 const rows=data[page]||[];
 const filtered=useMemo(()=>rows.filter(x=>(x.name+x.sku+x.category).toLowerCase().includes(query.toLowerCase())&&(status==='전체'||x.status===status)),[rows,query,status]);
 const meta=sections[page]||['준비 중','이 메뉴는 다음 연동 단계에서 활성화됩니다.'];
 const ui=pageUi[page];
 const save=async()=>{if(!editor.name.trim())return;const resource=getCloudResource(page);const cloud=session&&resource;if(cloud){setSyncing(true);const q=editor.id?supabase.from(resource.table).update(toCloud[page](editor)).eq('id',editor.id):supabase.from(resource.table).insert(toCloud[page](editor));const{data:items,error}=await q.select().single();setSyncing(false);if(error)return setToast(error.code==='23505'?'코드가 중복되었습니다. 고유한 값을 입력해 주세요.':'저장 권한을 확인해 주세요.');const saved=fromCloud[page](items);setData(d=>({...d,[page]:editor.id?d[page].map(x=>x.id===editor.id?saved:x):[saved,...d[page]]}))}else setData(d=>({...d,[page]:editor.id?d[page].map(x=>x.id===editor.id?editor:x):[{...editor,id:Date.now()},...d[page]]}));setEditor(null);setToast(cloud?'클라우드에 저장되었습니다.':'관리 설정이 저장되었습니다.')};
 const confirmDelete=async()=>{const resource=getCloudResource(page);if(session&&resource){const{error}=await supabase.from(resource.table).delete().eq('id',remove.id);if(error)return setToast('삭제 권한을 확인해 주세요.')}setData(d=>({...d,[page]:d[page].filter(x=>x.id!==remove.id)}));setRemove(null);setToast('항목을 삭제했습니다.')};
 const sendMagicLink=async()=>{if(!email.includes('@'))return setToast('이메일을 확인해 주세요.');const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});if(error)return setToast('로그인 링크 발송에 실패했습니다.');setAuthOpen(false);setToast('이메일로 로그인 링크를 보냈습니다.')};
 const runKakaoDelay=async()=>{if(!session)return setToast('관리자 클라우드 로그인이 필요합니다.');setSyncing(true);const{data:result,error}=await supabase.functions.invoke('send-kakao-shipping-delays',{body:{limit:20}});setSyncing(false);if(error){const message=error?.context?.status===503?'웹훅 비밀값 4개를 먼저 설정해 주세요.':'알림 실행에 실패했습니다.';return setToast(message)}setToast(`지연 ${result.scanned}건 확인 · ${result.sent}건 발송 · ${result.failed}건 재시도`)};
 const exportCsv=()=>{const csv=['이름,코드,분류,가격,재고,상태',...filtered.map(x=>[x.name,x.sku,x.category,x.price,x.stock,x.status].join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`korual-${page}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="app">
  {mobile&&<button className="navScrim" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}/>}
  <aside className={mobile?'open':''}><div className="brand">KORUAL<small>COMMERCE ADMIN</small></div><nav>{nav.map(([id,label,Icon])=><React.Fragment key={id}>{groupBefore[id]&&<small className="navGroup">{groupBefore[id]}</small>}<button className={page===id?'active':''} onClick={()=>{setPage(id);setEditor(null);setMobile(false)}}><Icon size={18}/><span>{label}</span>{id==='orders'&&<b>{data.orders.filter(x=>x.status!=='배송 완료').length}</b>}</button></React.Fragment>)}</nav><a href="https://korual.cafe24.com/" target="_blank">쇼핑몰 바로가기 ↗</a></aside>
  <main><header><button className="icon mobile" aria-label="메뉴 열기" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="topContext"><span>Commerce OS</span><b>운영센터</b></div><div className="global"><Search size={17}/><input aria-label="전체 검색" placeholder="전체 검색 (Ctrl + K)" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘K</kbd></div><button className="topIcon" aria-label="도움말"><HelpCircle size={18}/></button><button className="topIcon notification" aria-label="알림"><Bell size={18}/><i>{data.orders.filter(x=>x.status!=='배송 완료').length}</i></button><button className={'cloud '+(session?'online':'')} onClick={()=>session?supabase.auth.signOut():setAuthOpen(true)}>{session?<LogOut size={15}/>:<LogIn size={15}/>}<span>{syncing?'동기화 중':session?'클라우드 연결':'로컬 모드'}</span></button><div className="admin"><span>관리자</span><small>{session?.user?.email||'로그인 필요'}</small></div></header>
   <section className="workspace"><div className="title"><div><div className="breadcrumb">KORUAL <ChevronRight size={12}/> {meta[0]}</div><h1>{meta[0]}</h1><p>{meta[1]}</p></div><div className="titleActions">{page==='automation'&&<button className="secondary" onClick={runKakaoDelay}><Zap size={17}/>지연 알림 지금 실행</button>}{page!=='dashboard'&&<button className="primary" onClick={()=>setEditor({...blank})}><Plus size={17}/>{ui.add}</button>}</div></div>
   {page==='dashboard'?<Dashboard data={data} go={setPage}/>:<><div className="stats"><Stat label={ui.stats[0]} value={rows.length}/><Stat label={ui.stats[1]} value={rows.filter(x=>!['품절','초안','설정 필요'].includes(x.status)).length}/><Stat label={ui.stats[2]} value={rows.reduce((a,x)=>a+(Number(x.stock)||0),0)}/><Stat label={ui.stats[3]} value={(ui.money?'₩':'')+rows.reduce((a,x)=>a+(Number(x.price)||0),0).toLocaleString()}/></div>
    <div className="toolbar"><label><Search size={17}/><input placeholder={`${ui.columns[0]}, ${ui.columns[1]}, ${ui.columns[2]} 검색`} value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="전체">전체 상태</option>{[...new Set(rows.map(x=>x.status))].map(x=><option key={x}>{x}</option>)}</select><button onClick={exportCsv}><Download size={16}/>CSV 내보내기</button></div>
    <div className="table"><table><thead><tr>{ui.columns.map(x=><th key={x}>{x}</th>)}<th>관리</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td data-label={ui.columns[0]}><strong>{x.name}</strong><small>#{x.id}</small></td><td data-label={ui.columns[1]}>{x.sku}</td><td data-label={ui.columns[2]}>{x.category}</td><td data-label={ui.columns[3]}>{ui.money&&Number(x.price)>0?'₩':''}{Number(x.price).toLocaleString()}</td><td data-label={ui.columns[4]}>{x.stock}</td><td data-label={ui.columns[5]}><i className={['품절','초안','설정 필요','경고'].some(s=>x.status.includes(s))?'off':''}>{x.status}</i></td><td data-label="관리"><button className="icon" aria-label={`${x.name} 수정`} onClick={()=>setEditor({...x})}><Pencil size={16}/></button><button className="icon danger" aria-label={`${x.name} 삭제`} onClick={()=>setRemove(x)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><Search size={24}/><strong>검색 결과가 없습니다</strong><span>검색어나 상태 필터를 변경해 보세요.</span></div>}</div></>}</section></main>
  <nav className="bottomNav" aria-label="모바일 주요 메뉴">{mobileNav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setEditor(null)}}><Icon size={20}/><span>{label.replace(' 관리','')}</span>{id==='orders'&&data.orders.filter(x=>x.status!=='배송 완료').length>0&&<b>{data.orders.filter(x=>x.status!=='배송 완료').length}</b>}</button>)}<button className={mobile?'active':''} onClick={()=>setMobile(true)}><Menu size={20}/><span>전체</span></button></nav>
  {editor&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setEditor(null)}><div className="drawer"><div className="drawerHead"><div><h2>{editor.id?`${meta[0]} 수정`:ui.add}</h2><p>필수 정보를 확인하고 변경사항을 저장하세요.</p></div><button className="icon" aria-label="닫기" onClick={()=>setEditor(null)}><X/></button></div><div className="form"><Field label={`${ui.fields[0]} *`} value={editor.name} onChange={name=>setEditor({...editor,name})}/><Field label={ui.fields[1]} value={editor.sku} onChange={sku=>setEditor({...editor,sku})}/><div className="grid"><Field label={ui.fields[2]} value={editor.category} onChange={category=>setEditor({...editor,category})}/><Field label={ui.fields[3]} value={editor.status} onChange={status=>setEditor({...editor,status})}/><Field label={ui.fields[4]} type="number" value={editor.price} onChange={price=>setEditor({...editor,price})}/><Field label={ui.fields[5]} type="number" value={editor.stock} onChange={stock=>setEditor({...editor,stock})}/></div>{page==='orders'&&<div className="shippingFields"><h3>배송지연 알림 기준</h3><Field label="수신 전화번호" value={editor.customerPhone||''} onChange={customerPhone=>setEditor({...editor,customerPhone})}/><div className="grid"><Field label="출고 예정일" type="datetime-local" value={editor.shippingDueAt||''} onChange={shippingDueAt=>setEditor({...editor,shippingDueAt})}/><Field label="실제 출고일" type="datetime-local" value={editor.shippedAt||''} onChange={shippedAt=>setEditor({...editor,shippedAt})}/></div><Field label="송장번호" value={editor.trackingNumber||''} onChange={trackingNumber=>setEditor({...editor,trackingNumber})}/><p>출고 예정일이 지났고 실제 출고일이 비어 있으면 매시간 알림 대기열에 추가됩니다.</p></div>}</div><div className="drawerFoot"><button onClick={()=>setEditor(null)}>취소</button><button className="primary" onClick={save}><Check size={17}/>변경사항 저장</button></div></div></div>}
  {remove&&<div className="overlay"><div className="modal"><AlertTriangle/><h2>정말 삭제하시겠습니까?</h2><p><strong>{remove.name}</strong><br/>삭제한 항목은 복구할 수 없습니다.</p><div><button onClick={()=>setRemove(null)}>취소</button><button className="delete" onClick={confirmDelete}>삭제</button></div></div></div>}
  {authOpen&&<div className="overlay"><div className="modal auth"><Cloud/><h2>관리자 클라우드 연결</h2><p>관리자 이메일로 일회용 로그인 링크를 받습니다.</p><input type="email" placeholder="admin@korual.com" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendMagicLink()}/><div><button onClick={()=>setAuthOpen(false)}>취소</button><button className="primary" onClick={sendMagicLink}>링크 받기</button></div></div></div>}
  {toast&&<div className="toast" role="status" aria-live="polite"><Check size={18}/>{toast}</div>}
 </div>
}
function Stat({label,value}){return <div className="stat"><small>{label}</small><strong>{value}</strong><span>실시간 저장</span></div>}
function Dashboard({data,go}){const pending=data.orders.filter(x=>x.status!=='배송 완료');const low=data.products.filter(x=>Number(x.stock)<20);return <div className="dashboard"><div className="kpis"><Stat label="오늘 주문" value={data.orders.length}/><Stat label="예상 매출" value={'₩'+data.orders.reduce((a,x)=>a+Number(x.price||0),0).toLocaleString()}/><Stat label="활성 상품" value={data.products.filter(x=>x.status==='판매 중').length}/><Stat label="입금 확인 필요" value={pending.length}/><Stat label="재고 경보" value={low.length}/></div><div className="dashGrid"><DashPanel title="입금 확인이 필요한 주문" action={()=>go('orders')} rows={pending.map(x=>[x.sku,x.name,'₩'+Number(x.price).toLocaleString(),x.status])}/><DashPanel title="재고 부족 상품" action={()=>go('products')} rows={low.map(x=>[x.sku,x.name,x.stock+'개',x.status])}/></div><div className="dashBottom"><section className="health"><h3>연동 상태</h3>{data.integrations.map(x=><button key={x.id} onClick={()=>go('integrations')}><span>{x.name}<small>{x.category}</small></span><i className={x.status==='설정 필요'?'warn':''}>{x.status}</i></button>)}</section><section className="funnel"><h3>방문자 및 전환 흐름</h3><div className="bars">{data.analytics.map((x,i)=><div key={x.id}><span>{x.name}</span><b style={{width:(82-i*20)+'%'}}></b><strong>{x.price.toLocaleString()}</strong></div>)}</div><button onClick={()=>go('analytics')}>통계 전체 보기 →</button></section><section className="activity"><h3>운영 우선순위</h3><ol><li><b>1</b>계좌이체 입금 확인</li><li><b>2</b>저재고 상품 보충</li><li><b>3</b>Cafe24 OAuth 연결</li><li><b>4</b>SEO 콘텐츠 발행</li></ol></section></div></div>}
function DashPanel({title,rows,action}){return <section className="dashPanel"><header><h3>{title}</h3><button onClick={action}>전체 보기 →</button></header><div>{rows.length?rows.map((r,i)=><p key={i}>{r.map((c,j)=><span key={j}>{c}</span>)}</p>):<em>확인할 항목이 없습니다.</em>}</div></section>}
function Field({label,value,onChange,type='text'}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
createRoot(document.getElementById('root')).render(<App/>);
