-- Applied to Supabase project dtmmjkikyfgkeimhevso on 2026-09-19.
-- KORUAL platform core: module registry, request idempotency, lifecycle audit.

create table if not exists public.platform_modules (
  module_key text primary key,
  name text not null,
  description text not null default '',
  category text not null default 'platform',
  status text not null default 'planned'
    check (status in ('live','beta','ready','planned','degraded','disabled')),
  route text,
  icon text,
  sort_order integer not null default 100,
  enabled boolean not null default true,
  capabilities text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_modules_key_format check (module_key ~ '^[a-z0-9][a-z0-9_-]{1,63}$')
);

alter table public.platform_modules enable row level security;

drop policy if exists "platform_modules_server_only" on public.platform_modules;
create policy "platform_modules_server_only"
on public.platform_modules
as restrictive
for all
to anon, authenticated
using (false)
with check (false);

create index if not exists platform_modules_enabled_sort_idx
  on public.platform_modules (enabled, sort_order, module_key);

drop trigger if exists platform_modules_touch_updated_at on public.platform_modules;
create trigger platform_modules_touch_updated_at
before update on public.platform_modules
for each row execute function public.touch_updated_at();

insert into public.platform_modules
(module_key,name,description,category,status,route,icon,sort_order,enabled,capabilities,metadata)
values
  ('life','생활서비스','청소·이사·인터넷·정수기·인테리어','marketplace','live','#services','home',10,true,array['quote','compare'],'{}'),
  ('price','가격비교','시장 기준가·견적·추가비용 위험','marketplace','live','#compare','price',20,true,array['benchmark','compare'],'{}'),
  ('travel','여행·항공','항공편·여정·여행 플래너','travel','beta',null,'plane',30,true,array['planner'],'{}'),
  ('map','지도 허브','지역·공항·서비스 거점 탐색','travel','beta',null,'map',40,true,array['locations'],'{}'),
  ('notice','공지·운영','공지·점검·긴급 알림 센터','operations','ready',null,'bell',50,true,array['notices'],'{}'),
  ('partner','파트너','업체·공급사·제휴 연결 관리','marketplace','beta',null,'building',60,true,array['providers','suppliers'],'{}'),
  ('data','데이터','요청·예약·가격·연동 현황','operations','live','#data-overview','database',70,true,array['analytics'],'{}'),
  ('control','Control Center','운영·보안·자동화 통합 관제','operations','beta',null,'dashboard',80,true,array['ops','security','automation'],'{}')
on conflict (module_key) do update set
  name=excluded.name,
  description=excluded.description,
  category=excluded.category,
  status=excluded.status,
  route=excluded.route,
  icon=excluded.icon,
  sort_order=excluded.sort_order,
  enabled=excluded.enabled,
  capabilities=excluded.capabilities,
  metadata=public.platform_modules.metadata || excluded.metadata,
  updated_at=now();

alter table public.service_requests
  add column if not exists idempotency_key text;

create unique index if not exists service_requests_idempotency_key_uidx
  on public.service_requests (idempotency_key)
  where idempotency_key is not null;

create table if not exists public.service_request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.service_requests(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  actor_type text not null default 'system'
    check (actor_type in ('system','customer','provider','admin','automation')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.service_request_events enable row level security;

drop policy if exists "service_request_events_server_only" on public.service_request_events;
create policy "service_request_events_server_only"
on public.service_request_events
as restrictive
for all
to anon, authenticated
using (false)
with check (false);

create index if not exists service_request_events_request_created_idx
  on public.service_request_events (request_id, created_at desc);

create index if not exists service_request_events_type_created_idx
  on public.service_request_events (event_type, created_at desc);

create or replace function public.record_service_request_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_event_type text;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'created';

    insert into public.service_request_events
      (request_id,event_type,from_status,to_status,actor_type,metadata)
    values
      (new.id,v_event_type,null,new.status,'system',
       jsonb_build_object('source',new.source,'request_code',new.request_code));

    insert into public.cloud_events
      (event_type,source,aggregate_type,aggregate_id,payload,status)
    values
      ('marketplace.service_request.created','marketplace','service_request',new.id::text,
       jsonb_build_object('request_code',new.request_code,'status',new.status),'queued');

    return new;
  end if;

  if tg_op = 'UPDATE' and new.status is distinct from old.status then
    v_event_type := 'status_changed';

    insert into public.service_request_events
      (request_id,event_type,from_status,to_status,actor_type,metadata)
    values
      (new.id,v_event_type,old.status,new.status,'system',
       jsonb_build_object('request_code',new.request_code));

    insert into public.cloud_events
      (event_type,source,aggregate_type,aggregate_id,payload,status)
    values
      ('marketplace.service_request.status_changed','marketplace','service_request',new.id::text,
       jsonb_build_object('request_code',new.request_code,'from_status',old.status,'to_status',new.status),'queued');
  end if;

  return new;
end;
$$;

revoke all on function public.record_service_request_lifecycle() from public, anon, authenticated;

drop trigger if exists service_requests_lifecycle_event_trg on public.service_requests;
create trigger service_requests_lifecycle_event_trg
after insert or update of status on public.service_requests
for each row execute function public.record_service_request_lifecycle();
